" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

"colorscheme vividchalk
colorscheme slate

"set guifont=Courier\ 10\ Pitch\ 11
" set guifont=Inconsolata:h20            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
"set background=light              " Background.
"set lines=50 columns=120          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar


