. ~/dotfiles/bash/env
. ~/dotfiles/bash/config
. ~/dotfiles/bash/aliases

. ~/dotfiles/bash/rea

. ~/dotfiles/bash/git-completion

. ~/dotfiles/bash/aws
. ~/dotfiles/bash/docker


### PROMPT OPTIONS
export GIT_PROMPT_THEME=Dima
# Default - 5mins, change to 3hr (360mins)
export GIT_PROMPT_FETCH_TIMEOUT=180
. ~/dotfiles/bash/bash-git-prompt/gitprompt.sh


# Built executables by the stack tool will be symlink'd into ~/.local/bin
export PATH="$HOME/.local/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
