. ~/dotfiles/bash/config
. ~/dotfiles/bash/aliases

. ~/dotfiles/bash/rea

. ~/dotfiles/bash/git-completion

. ~/dotfiles/bash/aws
. ~/dotfiles/bash/docker

# asdf version manager
. ~/.asdf/asdf.sh
. ~/.asdf/completions/asdf.bash

# GPG
export GPG_TTY=$(tty)

### PROMPT OPTIONS
export GIT_PROMPT_THEME=Dima
# Default - 5mins, change to 3hr (360mins)
export GIT_PROMPT_FETCH_TIMEOUT=180
. ~/dotfiles/bash/bash-git-prompt/gitprompt.sh

# Built executables by the stack tool will be symlink'd into ~/.local/bin
export PATH="$HOME/.local/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
# Go
export PATH="$HOME/go/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion



